/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenericObjectPool {
  constructor(size: number)
  acquire(): number
  acquireAsync(timeoutMs?: number | undefined | null): Promise<number>
  release(idx: number): void
  add(idx: number): void
  removeOne(): number | null
  availableCount(): number
  size(): number
  pendingCount(): number
  destroy(): void
}
