/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenericObjectPool {
  constructor(initialValues: Array<object>)
  acquire(): object
  acquireAsync(timeoutMs?: number | undefined | null): Promise<object>
  release(resource: object): void
  add(resource: object): void
  removeOne(): boolean
  availableCount(): number
  size(): number
  pendingCount(): number
  destroy(): void
}
