/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenericObjectPool {
  constructor(initialValues: Array<unknown>)
  acquire(): Promise<unknown>
  release(resource: unknown): void
  add(resource: unknown): void
  removeOne(): boolean
  availableCount(): number
}
